- name: apt update and install lizardfs-metalogger
  apt: name=lizardfs-metalogger update_cache=yes

- name: chunk cfg file
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'mfsmetalogger.cfg', dest: '/etc/mfs/mfsmetalogger.cfg' }
    - { src: 'lizardfs-metalogger', dest: '/etc/default/lizardfs-metalogger' }

- name: start service lizardfs-metalogger
  service: name=lizardfs-metalogger state=started

  