# - hosts: all
#   sudo: yes
#   gather_facts: no
#   remote_user: vagrant
  
#   roles:
#     - common

- hosts: master
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  roles:
    - master
    
- hosts: shadow
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  roles:
    - shadow

- hosts: chunk
  sudo: yes
  gather_facts: yes
  remote_user: vagrant

  roles:
    - chunk

- hosts: meta
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  roles:
    - meta
    
- hosts: cgi
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  roles:
    - cgi
    
- hosts: client
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  roles:
    - client
    
