  - name: apt update and install lizardfs-master
    apt: name=lizardfs-master update_cache=yes

  - name: mfs cfg files
    copy: src=mfsmaster.cfg dest=/etc/mfs/mfsmaster.cfg owner=root group=root mode=0644

  - name: mfs cfg files
    copy: src=mfsexports.cfg dest=/etc/mfs/mfsexports.cfg owner=root group=root mode=0644

  - name: mfs cfg files
    copy: src=mfsgoals.cfg dest=/etc/mfs/mfsgoals.cfg owner=root group=root mode=0644

  - name: mfs cfg files
    copy: src=mfstopology.cfg dest=/etc/mfs/mfstopology.cfg owner=root group=root mode=0644

  - name: /var/lib/mfs
    file: path=/var/lib/mfs state=directory owner=mfs group=mfs mode=0755

  - name: /var/lib/mfs/metadata.mfs
    copy: src=metadata.mfs dest=/var/lib/mfs/metadata.mfs owner=mfs group=mfs mode=0644
    
  - name: lizardfs-master file
    copy: src=lizardfs-master dest=/etc/default/lizardfs-master owner=root group=root mode=0644

  - name: lizardfs-master service
    service: name=lizardfs-master state=started
  
                