- name: install lizardfs-client
  yum: name={{ item }}
  with_fileglob:
    - /usr/local/src/lizardfs-client*

- name: /mnt/lizardfs dir
  file: path=/mnt/lizardfs state=directory

- name: mount lizardfs
  command: mfsmount /mnt/lizardfs

- command: mfssetgoal 2 /mnt/lizardfs

  