- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - common

- hosts: master
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - master

- hosts: shadow
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - shadow

- hosts: chunk
  sudo: yes
  gather_facts: yes
  remote_user: root

  roles:
    - chunk

- hosts: meta
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - meta

- hosts: cgi
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - cgi
    
- hosts: client
  sudo: yes
  gather_facts: no
  remote_user: root
  
  roles:
    - client
    
