- name: apt update and install lizardfs-client
  apt: name=lizardfs-client update_cache=yes

- name: /mnt/lizardfs dir
  file: path=/mnt/lizardfs state=directory

- name: mount lizardfs
  command: mfsmount /mnt/lizardfs

  